USE [master]
GO

/****** Object:  Database [PersonasCentroDeAnalisis]    Script Date: 25/11/2021 13:28:07 ******/
CREATE DATABASE [PersonasCentroDeAnalisis]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PersonasCentroDeAnalisis', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PersonasCentroDeAnalisis.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PersonasCentroDeAnalisis_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PersonasCentroDeAnalisis_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PersonasCentroDeAnalisis].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PersonasCentroDeAnalisis] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PersonasCentroDeAnalisis] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PersonasCentroDeAnalisis] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PersonasCentroDeAnalisis] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PersonasCentroDeAnalisis] SET ARITHABORT OFF 
GO

ALTER DATABASE [PersonasCentroDeAnalisis] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PersonasCentroDeAnalisis] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PersonasCentroDeAnalisis] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PersonasCentroDeAnalisis] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PersonasCentroDeAnalisis] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PersonasCentroDeAnalisis] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PersonasCentroDeAnalisis] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PersonasCentroDeAnalisis] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PersonasCentroDeAnalisis] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PersonasCentroDeAnalisis] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PersonasCentroDeAnalisis] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PersonasCentroDeAnalisis] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PersonasCentroDeAnalisis] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PersonasCentroDeAnalisis] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PersonasCentroDeAnalisis] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PersonasCentroDeAnalisis] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PersonasCentroDeAnalisis] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PersonasCentroDeAnalisis] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PersonasCentroDeAnalisis] SET  MULTI_USER 
GO

ALTER DATABASE [PersonasCentroDeAnalisis] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PersonasCentroDeAnalisis] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PersonasCentroDeAnalisis] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PersonasCentroDeAnalisis] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PersonasCentroDeAnalisis] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PersonasCentroDeAnalisis] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [PersonasCentroDeAnalisis] SET QUERY_STORE = OFF
GO

ALTER DATABASE [PersonasCentroDeAnalisis] SET  READ_WRITE 
GO

